name: Tesenso CI/CD Pipeline

on:
  push:
    branches: [ "read-pom" , "master", "stored-debain", "main"]
#  pull_request:
#    branches: [ "master" ]

env:
  MY_VAR: ""

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
#      - name: checkout
#        uses: actions/checkout@v3
#
#      - name: Set up JDK 11
#        uses: actions/setup-java@v3
#        with:
#          java-version: '11'
#          distribution: 'temurin'
#          cache: maven
#
#      - name: Build tesenso middleware core
#        run: mvn clean package -DskipTests

#      - name: Get artifact id & rename debian file name
#        run: |
#            sudo apt-get install xmlstarlet
#            ARTIFACT_ID=$(xmlstarlet sel -N x=http://maven.apache.org/POM/4.0.0 -t -v "/x:project/x:artifactId" pom.xml)
#            VERSION=$(xmlstarlet sel -N x=http://maven.apache.org/POM/4.0.0 -t -v "/x:project/x:version" pom.xml)
#            FILE_NAME="${ARTIFACT_ID}-${VERSION}.deb"
#            MY_VAR=FILE_NAME
#            cd application/target/
#            mv thingsboard.deb "$FILE_NAME"

#      - name: Upload artifact
#        uses: actions/upload-artifact@v2
#        with:
#          name: upload-thingsboard
#          path: application/target/thingsboard.deb
      - name: Create file
        run: echo "Hello, world!" > example.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
            name: my-artifact
            path: example.txt



  download:
    runs-on: ubuntu-latest
    needs: upload
    steps:
      - name: checkout
        uses: actions/checkout@v3
#        with:
#          repository: ahasanhabib85/thingsboard-storage
#          ref: main

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: my-artifact


      - name: Upload large file into github large file storage
        run: |
            pwd
            echo "-------------------"
            git branch
            git config --global user.email "habib.ahasan@selise.ch"
            git config --global user.name "ahasanhabib85"
            git lfs track "*.txt"
            git add example.txt
            git commit -m "Add large file"
            git pull origin main
            git push origin main

#      - name: Install Git
#        run: |
#            sudo apt-get update
#            sudo apt-get install git
#            git config --global user.email "habib.ahasan@selise.ch"
#            git config --global user.name "ahasanhabib85"
#
#      - name: Pull changes from repository
#        run: git pull origin main
#
#      - name: Add changes to Git
#        run: |
#          git checkout main
#          git add example.txt
#
#      - name: Commit changes to Git
#        run: |
#          git commit -m "Update example.txt"
#          ls
#
#      - name: Push changes to repository
#        uses: ad-m/github-push-action@v0.5.0
#        with:
#            github_token: ${{ secrets.GITHUB_TOKEN }}
#            branch: main



#      - name: Upload large file into github large file storage
#        run: |
#          ls
#          pwd
#          git config --global user.email "habib.ahasan@selise.ch"
#          git config --global user.name "ahasanhabib85"
#          git checkout main
#          git lfs track "*.deb"
#          git add thingsboard.deb
#          git commit -m "Add large file"
#          git pull origin main
#          git push origin main


      

#      - name: Install git-lfs
#        run: |
#          curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
#          sudo apt-get install git-lfs
#          git lfs install
#


#      - name: Transfer to remote server
#        uses: appleboy/scp-action@master
#        with:
#          host: ${{ secrets.SERVER_IP }}
#          username: ${{ secrets.SERVER_USERNAME }}
#          password: ${{ secrets.SERVER_PASSWORD }}
#          port: ${{ secrets.SERVER_PORT }}
#          source: 'application/target/*.deb'
#          target: '/opt/tesenso'


#  deploy:
#    runs-on: ubuntu-latest
#    needs: build
#    steps:
#      - name: Deploy to the server
#        uses: appleboy/ssh-action@master
#        with:
#          host: ${{ secrets.SERVER_IP }}
#          username: ${{ secrets.SERVER_USERNAME }}
#          password: ${{ secrets.SERVER_PASSWORD }}
#          port: ${{ secrets.SERVER_PORT }}
#          script: |
#            sudo chmod -R 777 /opt/tesenso/application/target/*
#            sudo dpkg -i /opt/tesenso/application/target/*.deb